theme: jekyll-theme-cayman
plugins:
      - jekyll-redirect-from
install_url: https://accounts.google.com/o/oauth2/v2/auth?client_id=141962813513-bsr1ggi5gcgflu83u9nq22frihh5cda3.apps.googleusercontent.com&response_type=token&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.install&redirect_uri=https%3A%2F%2Fsasdf.github.io%2FGUpload%2Fredirect
